### ISSUE TITLE
Output is showing more FSI information

### ISSUE THREAD

**Issue by 64J0** [juergenhoetzel/ob-fsharp#1]
## Description:

When testing this package locally, I'm getting a different result:

```
#+BEGIN_SRC fsharp :var str="World!" :exports both
sprintf "Hello %s" str
#+END_SRC

#+RESULTS:
: sprintf "Hello %s" str;;
: val it: string = "Hello World!"
```

As you can see, it's printing the information regarding the function and some type annotations, which is common to `dotnet fsi`.

Have you ever faced this?

**Comment by juergenhoetzel** [comment]
> ``.
> 
> Have you ever faced this?

I can confirm this issue and tracked it down to this change https://github.com/fsharp/emacs-fsharp-mode/pull/311

It fixed hanging inferior fsharp processes but also introduced the extra `echo` of the input line.
I see no easy way to set line-buffering for `non-pty` processes: https://www.gnu.org/software/emacs/manual/html_node/efaq-w32/Subprocess-buffering.html
 :disappointed:

**Comment by 64J0** [comment]
I thought about using this dirty strategy:

```
#+BEGIN_SRC sh :shebang "#!/usr/bin/env -S dotnet fsi" :file-ext "fsx" :tangle finance-shebang.fsx
  printfn "abc"
#+END_SRC
```

But was not able to make it work in my computer. I get this kind of error:

* error FS0226: The file extension of '/tmp/babel-aaa/sh-script-bbb' is not recognized. Source files must have extension .fs, .fsi, .fsx, .fsscript, .ml or .mli.

Reference for the shebang: https://learn.microsoft.com/en-us/dotnet/fsharp/whats-new/fsharp-6#f-tooling-pin-the-sdk-version-of-your-f-scripts.

**Comment by 64J0** [comment]
Another approach would be combining the FSharp script and the Shell SRC block:

1. First, tangle the FSharp code to the appropriate file;
2. Then, run it in the shell block.

---

Practical example [repository link](https://github.com/64J0/literate-prog-finance):

* Initial state: `#+PROPERTY: header-args :var X_0=1e4 :var Y=1e3 :var H=1.01 :var N=120`

The source block that is going to be tangled:

```
#+NAME: finance-fsx
#+BEGIN_SRC fsharp :results value replace :exports code :tangle finance.fsx
  let rec calcMoney (x0: float) (y: float) (h: float) (nMonth: int): float =
      match nMonth with
      | 0 -> x0
      | _ when (nMonth > 0) ->
          let previousValue = calcMoney (x0) (y) (h) (nMonth - 1)
          (previousValue * h) + y
      | _ -> 0

  let main () =
      let resultMoney = calcMoney (X_0) (Y) (H) (N)

      printfn """
      Initial money: %.2f
      Addition per month: %.2f
      Increase rate per month: %.2f
      Investment time: %i months
      Final value: %.2f moneys
      """ (X_0) (Y) (H) (N) (resultMoney)

  main ()
#+END_SRC
```

After tangling it, use this block:

```
#+NAME: run-fsx
#+BEGIN_SRC shell :results output
  dotnet fsi finance.fsx
#+END_SRC
```

Result:

```
#+RESULTS: run-fsx
: 
:     Initial money: 10000.00
:     Addition per month: 1000.00
:     Increase rate per month: 1.01
:     Investment time: 120 months
:     Final value: 263042.56 moneys
: 
```

**Comment by juergenhoetzel** [comment]
This should be fixed by workaround https://github.com/juergenhoetzel/ob-fsharp/commit/829728a4cdda1f4fb6c12bfdc4d1aa5741ca9b7c 
which post processes the `FSI` output which interleaves INPUT/OUTPUT when using the `pty` process type.

BTW: Much legacy `ob` and `ob-ocaml` involved here that would need some cleaning up. Any contribution is appreciated :smile:

**Comment by 64J0** [comment]
> BTW: Much legacy ob and ob-ocaml involved here that would need some cleaning up. Any contribution is appreciated smile

I would like to help, but I don't know much about it. Can you please send some links to clarify this feature @juergenhoetzel ?
